### ISSUE TITLE
docs: Improve installation and configuration documentation for non-container use cases

### ISSUE THREAD

**Issue by bmullan** [webmeshproj/node#2]
The current README file says:

> _The node binary is distributed as a container image or a standalone binary._   
> **To install the binary, download the latest release for your platform and architecture from the [releases page](https://github.com/webmeshproj/node/releases)**. To run the container image, pull the latest image from the GitHub container registry. The examples in this guide will use the image.

I use Ubuntu 22.04 on my machines and a lot of LXD Containers & VMs.

Docker is redundant in purpose/function to LXD and although I could run Docker & Docker apps I'd prefer not to incur that overhead.

So _I am interested in trying/installing the **webmesh binary**_.
 
But the README only gives more information about how to run/configure the Docker image and nothing further about how to run/configure the Binary version.   Info like:  available command line options etc.
 
_Is there any info about the install/configuration etc of the Binary webmesh?_

thanks
brian

**Comment by tinyzimmer** [comment]
The image is just the statically compiled binary copied into a container. All the arguments and everything are the same for both. That could certainly be made more apparent in the README or on the new website (https://webmeshproj.github.io/). 

In this vein, though, I want to make some distro packages probably. I run Arch myself and could handle putting together a PKGBUILD - but would be grateful for help with other OSes.

**Comment by tinyzimmer** [comment]
I've started a place for guides in the new website. This one in particular should hopefully start to make things a bit clearer: https://webmeshproj.github.io/guides/personal-vpn/

**Comment by bmullan** [comment]
@tinyzimmer 
_That new Guide looks good so far ... thanks!_

Brian

**Comment by tinyzimmer** [comment]
Closing this issue for now to keep things tidy - but feel free to open a new one if you run into any more issues.
